import { API_URL, OCP_APIM_KEY, JOB_CREATION_SWAGGER_URL, LOGIN_SWAGGER_URL } from '@env';

export const envData = {
  BASE_URL: API_URL ?? process.env.API_URL,
  APIM_KEY: OCP_APIM_KEY ?? process.env.OCP_APIM_KEY,
  JOB_CREATION_SWAGGER_URL: JOB_CREATION_SWAGGER_URL ?? process.env.JOB_CREATION_SWAGGER_URL,
  LOGIN_SWAGGER_URL: LOGIN_SWAGGER_URL ?? process.env.LOGIN_SWAGGER_URL,
};
